"""
Day 9 — argparse: turning your script into a real CLI tool

Today's mission: take your Day 6 Stale Account Detector and turn it
into a proper command-line tool that someone could pip-install and
use. By the end of tonight, this should work:

    python3 stale_detector.py --input sample_users.json --threshold 30
    python3 stale_detector.py --input sample_users.csv --output /tmp/r.txt
    python3 stale_detector.py --help

You're meeting `argparse`, the standard-library module for parsing
command-line flags. Every real Python CLI uses it (or a wrapper on
top like Click or Typer). It gives you `--help` for free, validates
types, and replaces every "what if the user passes garbage?" check
you'd write by hand.

You'll also start to feel why people split scripts into:
  - a LIBRARY module (iam_utils.py — pure functions)
  - a CLI module (stale_detector.py — argparse + main)
  - day-NN.py files (your learning sketches)

============================================================
GOAL 1 — Hello-world CLI
============================================================

Before touching the real tool, build the smallest possible argparse
example so the shape is clear. Put this in day_09.py:

    import argparse

    def main():
        parser = argparse.ArgumentParser(
            description="Day 9 sandbox — say hello to someone."
        )
        parser.add_argument("--name", default="world", help="who to greet")
        parser.add_argument("--shout", action="store_true", help="upper-case the greeting")
        args = parser.parse_args()

        greeting = f"Hello, {args.name}!"
        if args.shout:
            greeting = greeting.upper()
        print(greeting)

    if __name__ == "__main__":
        main()

Run it five different ways, in this order:

    python3 day_09.py
    python3 day_09.py --name Alice
    python3 day_09.py --name Alice --shout
    python3 day_09.py --shout
    python3 day_09.py --help              # ← free, generated by argparse

Things to notice:
  - `--help` prints automatically. You wrote zero lines for it.
  - `default="world"` makes `--name` optional.
  - `action="store_true"` makes `--shout` a flag (no value), defaulting to False.
  - `args.name`, `args.shout` — the parser hands you a tidy object whose
    attributes match the flag names.

============================================================
GOAL 2 — Build `stale_detector.py` as a real CLI
============================================================

Create a new file: `stale_detector.py` (sibling of iam_utils.py).
This is going to replace your Day 6 day_06.py as the canonical tool.

Skeleton:

    import argparse
    import json
    from iam_utils import load_users, find_stale, find_disabled, parse_signin
    from datetime import datetime

    def build_report(users, threshold_days):
        lines = []
        lines.append("=" * 60)
        lines.append("Stale Account Detector — Report")
        lines.append(f"Generated: {datetime.now().isoformat(timespec='seconds')}")
        lines.append(f"Users scanned: {len(users)}")
        lines.append(f"Stale threshold: {threshold_days} days")
        lines.append("=" * 60)
        lines.append("")
        lines.append("DISABLED ACCOUNTS:")
        for u in find_disabled(users):
            lines.append(f"  {u['displayName']:<25} {u['userPrincipalName']}")
        lines.append("")
        lines.append(f"STALE ACCOUNTS (>{threshold_days} days):")
        for u in find_stale(users, threshold_days):
            days = parse_signin(u)
            lines.append(f"  {u['displayName']:<25} {days} days  ({u['userPrincipalName']})")
        return "\n".join(lines)

    def main():
        parser = argparse.ArgumentParser(
            description="Detect stale and disabled accounts in a user export."
        )
        parser.add_argument("--input", required=True,
                            help="Path to user export (.csv or .json)")
        parser.add_argument("--threshold", type=int, default=90,
                            help="Days since last sign-in to consider stale (default: 90)")
        parser.add_argument("--output", default="stale_report.txt",
                            help="Path to write the report (default: stale_report.txt)")
        args = parser.parse_args()

        users = load_users(args.input)
        report = build_report(users, args.threshold)
        with open(args.output, "w") as f:
            f.write(report)
        print(report)
        print(f"\nReport saved to {args.output}")

    if __name__ == "__main__":
        main()

Notice the new argparse pieces:
  - `required=True` — argparse rejects the run with a clear error if
    --input is missing. You don't write the check; argparse does.
  - `type=int` — argparse converts the string "90" to int(90) for you.
    If the user passes "abc" it rejects with a clear error.

Try to run it now:

    python3 stale_detector.py --input sample_users.csv

It will probably explode — because `load_users()` only knows how to
read CSV. Goal 3 fixes that.

============================================================
GOAL 3 — Make load_users() format-aware
============================================================

In `iam_utils.py`, modify `load_users(filename)` to dispatch on
file extension. Skeleton:

    import csv
    import json

    def load_users(filename):
        if filename.endswith(".json"):
            with open(filename) as f:
                data = json.load(f)
            # Graph API wraps users in a "value" array
            return data["value"] if isinstance(data, dict) and "value" in data else data
        elif filename.endswith(".csv"):
            users = []
            with open(filename) as f:
                reader = csv.DictReader(f)
                for row in reader:
                    users.append(row)
            return users
        else:
            raise ValueError(f"Unsupported file extension: {filename}")

Notice three new things:
  - `.endswith(".json")` is a clean way to inspect the extension.
  - `isinstance(data, dict)` checks the type at runtime — handles the
    case where the JSON is already a flat list of users instead of a
    Graph-API-wrapped object.
  - `raise ValueError(...)` — first time you've RAISED an exception
    rather than catching one. This is how you signal "the caller
    asked for something I can't do." We'll use this more in Week 3.

Now both should work:

    python3 stale_detector.py --input sample_users.csv
    python3 stale_detector.py --input sample_users.json

Both should produce the same stale/disabled counts.

============================================================
GOAL 4 — Add --quiet
============================================================

Add a flag that suppresses the console print but still writes the
file:

    parser.add_argument("--quiet", action="store_true",
                        help="don't print the report to console")
    ...
    if not args.quiet:
        print(report)
    print(f"Report saved to {args.output}")     # always print this

Test:
    python3 stale_detector.py --input sample_users.json --quiet

This is the shape of every "I want to use this in a cron job" flag.

============================================================
STRETCH 5 — choices=
============================================================

Add an `--format` flag that picks between plain text and JSON output:

    parser.add_argument("--format", choices=["txt", "json"], default="txt",
                        help="output format")

Then in main, branch on `args.format`:

    if args.format == "json":
        payload = {
            "generated": datetime.now().isoformat(timespec="seconds"),
            "threshold_days": args.threshold,
            "stale": [u["userPrincipalName"] for u in find_stale(users, args.threshold)],
            "disabled": [u["userPrincipalName"] for u in find_disabled(users)],
        }
        with open(args.output, "w") as f:
            json.dump(payload, f, indent=2)
    else:
        with open(args.output, "w") as f:
            f.write(report)

`choices=` makes argparse reject any value that isn't in the list,
again with a clear error. Try `--format yaml` and watch it refuse.

============================================================
STRETCH 6 — Replace day_06.py with a redirect
============================================================

Day 6's day_06.py is now obsolete — stale_detector.py supersedes it.
Don't delete day_06.py (it's a historical artifact of your learning),
but add a comment at the top:

    # Day 6 milestone — superseded by stale_detector.py on Day 9.

This is real-world commit hygiene. Keep the old file as an artifact;
make it clear what replaces it.

============================================================
COMMIT
============================================================

    git add stale_detector.py iam_utils.py day_09.py day_06.py
    git commit -m "feat: day 9 — stale_detector CLI with argparse + format dispatch"
    git push

Things you're meeting today:
  - argparse: ArgumentParser, add_argument, parse_args
  - --help (free)
  - required=, default=, type=, action="store_true", choices=
  - .endswith() for extension dispatch
  - isinstance() for type checks at runtime
  - raise ValueError(...) — first time you raise rather than catch

Why this matters for IAM:
  Every internal automation tool eventually needs flags. Threshold,
  input file, output destination, dry-run mode, verbose mode. Doing
  this with argparse instead of sys.argv hand-parsing is the
  difference between "a script I wrote" and "a tool I can hand to
  a coworker."

Rules of the road:
  - 10-minute stuck rule.
  - Run `--help` after every add_argument change. It's the fastest
    way to see if the flag is wired up correctly.
"""
# Your code below.
import argparse

def main():
    parser = argparse.ArgumentParser(
        description="Day 9 sandbox — say hello to someone."
    )
    parser.add_argument("--name", default="world", help="who to greet")
    parser.add_argument("--shout", action="store_true", help="upper-case the greeting")
    args = parser.parse_args()

    greeting = f"Hello, {args.name}!"
    if args.shout:
        greeting = greeting.upper()
    print(greeting)

if __name__ == "__main__":
    main()